import "@/styles/index.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "react-toastify/dist/ReactToastify.css";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import Container from "../components/layout/container/Container";
import { ToastContainer } from "react-toastify";
import AuthProvider from "./AuthProvider";

export const metadata = {
  title: "ConDev | Casino Templates",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <AuthProvider>
          <Container>
            <main className="d-flex flex-column flex-grow-1 align-items-center justify-content-center" >{children}</main>
          </Container>
        </AuthProvider>
        <ToastContainer position="top-right" rtl theme="colored" />
      </body>
    </html>
  );
}
