// Bootstrap
import "@/styles/index.css";
import "bootstrap/dist/css/bootstrap.min.css";
// Swiper
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
// Fonts
import { fontIranSans, fontRokh } from "@/lib/fonts";
// Components
import Container from "../components/layout/container/Container";
import AuthProvider from "./AuthProvider";
import ToastProvider from "@/components/common/ToastProvider";

export const metadata = {
  title: "ConDev | Casino Templates",
  description: "Generated by create next app",
};

export default function RootLayout({ children , modal }) {
  return (
    <html
      lang="fa"
      dir="rtl"
      className={`${fontIranSans.variable} ${fontRokh.variable}`}
    >
      <body>
        <AuthProvider>
          <Container>
            {/* flex-grow-1 */}
            <main className="d-flex flex-column  align-items-center justify-content-center">
              {modal}
              {children}
            </main>
          </Container>
        </AuthProvider>
        <ToastProvider />
      </body>
    </html>
  );
}
