import "@/styles/index.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Container from "../components/layout/container/Container";
import Header from "@/components/layout/header/Header";
import Footer from "@/components/layout/footer/Footer";

export const metadata = {
  title: "ConDev | Casino Templates",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <Container>
          <Header />
          <main className="mb-5 pb-3">{children}</main>
          <Footer />
        </Container>
      </body>
    </html>
  );
}
